version: "3"

services:

   etracs-server:
      volumes:
         - ./dev_modules/admin:/services/modules/admin
         - ./dev_modules/etracs:/services/modules/etracs
         - ./dev_modules/financial:/services/modules/financial
         - ./dev_modules/jasper:/services/modules/jasper
         - ./dev_modules/rules:/services/modules/rules

         - ./dev_modules/treasury:/services/modules/treasury
         - ./dev_modules/_treasury.conf:/apps/etracs25/modules.conf.d/_treasury.conf

         ## mounted lib
         - ../../_res/lib/osiris2-report.jar:/apps/server/lib/osiris2-report.jar
         - ../../_res/lib/rameses-common2.jar:/apps/server/lib/rameses-common2.jar
