version: "3"

services:

  epayment-server:
    container_name: terminal-server
    image: ramesesinc/enterprise-common-server:255.05.001
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ./env.conf
      - ../../_res/env.conf
      - ../../_custom/env.conf
    ports: 
      - "8020:8070"
    volumes:
      - ../../_res/connections:/enterprise/connections/ext
      - ../../_custom/datasources/terminalds:/services/datasources/mainds

      - ./server:/enterprise/modules

      - ./client/reports:/apps/server/templates
      - ../../_custom/module-client/terminal:/apps/server/templates/custom
      - ../../_custom/output:/apps/server/output
